
services:
  backend:
    build: 
      context: ./incident-wizard-backend
      dockerfile: Dockerfile
    #image: ahmadscruggs1/my-backend:latest
    container_name: flask-backend
    ports:
      - "5000:5000"  # Host port : Container port
    # If your Flask code calls random-data-api or other external URLs, no extra config needed
    # environment:
    #   - FLASK_ENV=production
    # volumes:
    #   - ./backend:/app
    # depends_on:
    #   - db (if you had a database service, for instance)

  frontend:
    build:
      context: ./incident-wizard-ui
      dockerfile: Dockerfile
    #image: ahmadscruggs1/my-frontend:latest
    container_name: react-frontend
    ports:
      - "3000:80"  # Host port : Container's NGINX port
    # depends_on:
    #   - backend